#%RAML 1.0 Library

traits: 
  errorRespons: !include ../traits/helloTrait.raml
uses:
  messageType:  ../dataTypes/messageTypeLibrary.raml
  
securitySchemes:
  clientIDEnforcement: !include ../exchange_modules/9be525ca-2070-48e3-9316-f0b9178b7e1f/customesecurityscheme/1.0.0/customesecurityscheme.raml

types:
  helloType: !include ../dataTypes/helloWorldDataType.raml

resourceTypes:
  helloWorldCollection:
    get?:
      is: [errorRespons]
      responses:
        200:
          body:
            application/json:
              example: |
                <<exampleReference1>>
    post?:
      is: [errorRespons]
      securedBy:
        - clientIDEnforcement
      headers:
        To:
          example: "+14158557316"
        From: 
          example: "+918298082521"          
      body:
        application/json:
          type: [messageType.messageType]           
      responses:
        201:
          body:
            application/json:
              example: |
                <<exampleReference2>>
        
        

